#source : https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-22-04
---
- name: Install and configure Docker  # Nom du playbook
  hosts: webServer  # Spécifie les hôtes sur lesquels ce playbook doit être exécuté
  become: true  # Indique que les tâches doivent être exécutées avec des privilèges d'administrateur
  tasks:  # Début de la section des tâches
    - name: Update apt package index  # Nom de la tâche
      apt:
        update_cache: yes  # Met à jour l'index des paquets apt

    - name: Install aptitude  # Nom de la tâche pour installer aptitude
      apt:
        name: aptitude  # Nom du paquet à installer
        state: latest  # S'assure que la dernière version du paquet est installée
        update_cache: true  # Met à jour l'index des paquets apt

    - name: Install required system packages  # Nom de la tâche pour installer les paquets système requis
      apt:
        name:  # Liste des paquets à installer
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest  # S'assure que la dernière version des paquets est installée

    - name: Add Docker GPG apt Key  # Nom de la tâche pour ajouter la clé GPG de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg  # URL de la clé GPG
        state: present  # S'assure que la clé est présente

    - name: Add Docker Repository  # Nom de la tâche pour ajouter le dépôt Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable  # URL du dépôt Docker pour Ubuntu Jammy
        state: present  # S'assure que le dépôt est présent

    - name: Update apt and install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest  # Assure que la dernière version des paquets est installée
        update_cache: true  # Met à jour l'index des paquets apt avant l'installation

    - name: Install Docker Module for Python  # Nom de la tâche pour installer le module Docker pour Python
      pip:
        name: docker  # Nom du paquet pip à installer
        state: latest  # S'assure que la dernière version du module docker est installée
